name: Generate Sitemap
on:
  push:
    branches: [ main ]

# Added permissions block to fix Exit Code 128
permissions:
  contents: write

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate Sitemap
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate the sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://www.patiocoverkaty.net/

    - name: Commit and push sitemap
      run: |
        git config --global user.name 'sitemap-bot'
        git config --global user.email 'bot@noreply.github.com'
        git add sitemap.xml
        # The || exit 0 prevents failure if there are no changes to the sitemap
        git commit -m "Automated sitemap update" || exit 0
        git push
